name: Build container image

env:
  JAVA_VERSION: '21'

on:
  push:
    branches:
      - main
    #   - email-feature-branch
    #   - private-docs-rag-solution
    paths-ignore:
      - '**/*.md'
      - '.github/dependabot.yml'
      - '.github/workflows/dependabot-automerge.yml'

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: maven

      - name: "build-and-push-app"
        working-directory: app
        run: |
          ./mvnw -B quarkus:add-extension -Dextensions="quarkus-container-image-podman" &&
          ./mvnw -B clean package -DskipTests \
            -Dquarkus.container-image.builder=podman \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=true \
            -Dquarkus.container-image.tag=latest \
            -Dquarkus.container-image.additional-tags=${{ github.sha }} \
            -Dquarkus.container-image.registry=quay.io \
            -Dquarkus.container-image.group=rhappsvcs \
            -Dquarkus.container-image.name=parasol-insurance \
            -Dquarkus.container-image.username=rhappsvcs+parasol \
            -Dquarkus.container-image.password=${{ secrets.REGISTRY_PASSWORD }} \
            -Dquarkus.podman.platform=linux/amd64,linux/arm64
